myapp/config/routes.rb
Myapp::Application.routes.draw do
  devise_for :users

  resources :photos

  resources :albums

   root :to => 'albums#index'

end

myapp/app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :album_id,:asset,:poster
  belongs_to :album
  has_attached_file :asset
  has_attached_file :poster
  
  after_save :create_thumbnail

  def create_thumbnail
    if self.poster.url=="/posters/original/missing.png"
      @photo = self
      fileName = @photo.asset_file_name
      tmpFile = @photo.asset
      if fileName.rindex('.') && fileName.rindex('.') >=0
        thumb_base_name = "#{fileName[0,fileName.rindex('.')]}_thumbnail"
      else
        thumb_base_name = "#{fileName}_thumbnail"
      end
      thumbNailProcessor = Paperclip::Thumbnail.new(tmpFile, {:thumbnailBaseName => thumb_base_name,:time_offset => -1, :geometry => '50x50'}) 
      thumb_ext = 'png'
      thumb_content_type = 'image/png'
      fileObject = thumbNailProcessor.make
      
      # renaming file
      thumbnail_abs_path = File.absolute_path(fileObject)
      if thumbnail_abs_path.rindex('/') and thumbnail_abs_path.rindex('/')>=0
        thumbnail_new_abs_path = thumbnail_abs_path[0,thumbnail_abs_path.rindex('/')+1]+"#{thumb_base_name}.#{thumb_ext}"
      else
        thumbnail_new_abs_path = "#{thumb_base_name}.#{thumb_ext}"
      end
      File.rename(thumbnail_abs_path,thumbnail_new_abs_path)
      fileObject = File.new(thumbnail_new_abs_path)
      
      @photo.update_attributes(:poster=>fileObject)
    end
  end

end

myapp/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  # def index
    # @photos = Photo.all
# 
    # respond_to do |format|
      # format.html # index.html.erb
      # format.json { render json: @photos }
    # end
  # end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new
    if params[:album_id]
      @photo.album_id = params[:album_id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    if params["photo"] and params["photo"]["asset"]
      @photo = Photo.new(params[:photo])
  
      respond_to do |format|
        if @photo.save
          # @photo.create_thumbnail
          format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
          format.json { render json: @photo, status: :created, location: @photo }
        else
          format.html { render action: "new" }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to new_photo_path(:album_id=>params[:photo][:album_id])}
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @album = Album.find(@photo.album_id)
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to @album }
      format.json { head :no_content }
    end
  end
end

myapp/app/helpers/photos_helper.rb
module PhotosHelper
end

myapp/app/views/photos/_form.html.erb
<%= form_for @photo, :html=> {:multipart=>true} do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :album_id, :style=>"display:none;" %>
  <%= f.file_field :asset %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myapp/app/views/photos/edit.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

myapp/app/views/photos/index.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<h1>Listing photos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

myapp/app/views/photos/new.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

myapp/app/views/photos/show.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<p id="notice"><%= notice %></p>
<%= image_tag @photo.asset.url, :style=>"width:100px;height:100px;"%>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', @photo.album %>

myapp/app/views/photos/tindex.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<h1>Listing photos</h1>

<% @photos.each do |photo| %>
	<%= image_tag photo.asset.url, :style=>"width:100px;height:100px;"%>
    <%= link_to 'Show', photo %>
    <%= link_to 'Edit', edit_photo_path(photo) %>
    <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br />
<% end %>

<br />

<%= link_to 'New Photo', new_photo_path %>