myapp/config/routes.rb
Myapp::Application.routes.draw do
  devise_for :users

  resources :photos

  resources :albums

   root :to => 'albums#index'

end

myapp/app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title
  has_many :photos
  
  accepts_nested_attributes_for :photos
end

myapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    if current_user
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @albums }
      end
    else
      redirect_to :new_user_session
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new
    2.times do
      @album.photos.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @photos = params[:album].delete("photos_attributes")
    @album = Album.new(params[:album])
    @album.user_id = current_user.id

    respond_to do |format|
      if @album.save
        if @photos
          @photos.each do |key,value|
            @photo = Photo.new(value)
            @photo.album_id = @album.id
            @photo.save
            # @photo.create_thumbnail
          end
        end
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

myapp/app/helpers/albums_helper.rb
module AlbumsHelper
end

myapp/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <%= f.fields_for :photos do |builder| %>
  	<%= builder.file_field :asset%>
  	<br />
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myapp/app/views/albums/edit.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

myapp/app/views/albums/index.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
	<h1>Listing albums</h1>
	<% current_user.albums.each do |album| %>
		<div style="width:400px;height:100px;clear:both;">
			<div style="float:left;position:relative;top:50px;">
			    <b><%= album.title %></b>
			</div>
			<div style="float:left;position:relative;left:50px;">
				<% unless album.photos.empty?%>
			    	<%= image_tag album.photos[rand(album.photos.length)].poster.url, :style=>"max-height:100px;max-width:100px;height:100px;width:100px;" %>
			    <% else%>
			    	<%= image_tag "/images/no_preview.jpg", :style=>"max-height:100px;max-width:100px;height:100px;width:100px;" %>
				<% end %>
			</div>
			<div style="float:left;position:relative;left:100px;top:50px;">
		    <%= link_to 'View Album', album %>
			</div>
		</div>
<!-- 	    <%= link_to 'Edit', edit_album_path(album)  %> -->
<!-- 	    <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %> -->
	<% end %>
	<br />
	<%= link_to 'New Album', new_album_path %>
<% else %>
	<div style="font-size: 25px;height: 200px;text-align: center;position: relative;top: 110px;">
		<div style="height: 50%;">
			<%= link_to "Sign In", new_user_session_path %>
		</div>
		<div style="height: 50%;">
			<%= link_to "Sign Up", new_user_registration_path %>
		</div>
	</div>
<% end %>

myapp/app/views/albums/new.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

myapp/app/views/albums/show.html.erb
<% if current_user%>
	Welcome <%= current_user.email%>
	<%= link_to "Sign Out", destroy_user_session_path, :method=>:delete %>
	<br />
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<br />
<% end %>
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @album.title %>
</p>
<% @album.photos.each do |photo| %>
  	<%= image_tag photo.poster.url, :style=>"max-height:200px;max-width:200px;"%>
<!--     <%= link_to 'Show', photo %> -->
<!--     <%= link_to 'Edit', edit_photo_path(photo) %> -->
    <%= link_to 'delete', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<br />
<%= link_to "Add Photo", new_photo_path(:album_id=>@album.id)%>
<br />

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>